# If you wish to add a custom TurboModule or Fabric component in your app you
# will have to include the following autogenerated makefile.
# include $(GENERATED_SRC_DIR)/codegen/jni/Android.mk
# include $(CLEAR_VARS)

# Includes the MK file for `react-native-smartlook-analytics`
include $(NODE_MODULES_DIR)/react-native-smartlook-analytics/android/build/generated/source/codegen/jni/Android.mk
include $(CLEAR_VARS)
libreact_codegen_rncore \
libreact_codegen_SmartlookAnalytics \
libreact_debug \